### ISSUE TITLE
Logs coming through router are attributed to router

### ISSUE THREAD

**Issue by Artanicus** [echothrust/echofish#93]
Background:
I have an LXC container that runs an rsyslog receiver and pushes to SQL for echolog. All hosts logging into it up til now have been containers on the same host node (10.0.3.0/24) or the hostnode itself. Now I'm adding however other physical devices that log to the same loghost such as network gear. These hosts live on 10.0.10.0/24 and are routed by their default gw (10.0.10.1) to the 10.0.3.0/24 network where the loghost lives.

What's wrong:
Any messages coming outside the loghosts network segment get attributed for the router passing on the message, i.e. in my example to 10.0.10.1. Since echofish examples show using fromhost-ip, from the perspective of rsyslog this is Working as Intended, quoting from their property reference:
```
hostname | hostname from the message
source | alias for HOSTNAME
fromhost | hostname of the system the message was received from (in a relay chain, this is the system immediately in front of us and not necessarily the original sender). This is a DNS-resolved name, except if that is not possible or DNS resolution has been disabled.
fromhost-ip | The same as fromhost, but alsways as an IP address. Local inputs (like imklog) use 127.0.0.1 in this property.
```

Am I SOL since Echofish seems to need fromhost-ip instead of hostname? I could give my loghost a second ip address on the physical device's network and do DNS trickery to make sure they're accessing non-routed, but are there any other options?

I see #17 touches on this issue somewhat but what ever was implemented there doesn't mitigate this one.

**Comment by proditis** [comment]
Hello @Artanicus 

As far as echofish goes, we try to look for syslog client hosts by hostname, fqdn, IPv4 and (in theory) IPv6. 
```
SET @hostexists=(SELECT id FROM `host` WHERE fqdn=NEW.host or short=NEW.host or 
ip like NEW.host or INET6_NTOA(ip)=NEW.host);
```
So we should be able to work with any of the above.

Try to ensure that the router forwards the messages with the correct hostname defined and then create a filter for messages received from the router to log the original `hostname` instead of `fromhost-ip`.

@gadamo Has provided a great example there https://github.com/echothrust/echofish/issues/17#issuecomment-90115492

You may also need to check the rsyslog option `-c 4` on the router and `$PreserveFQDN on` config option on both router/echofish.

Take a look and let us know how it goes.

Pantelis

**Comment by Artanicus** [comment]
So if I'm understanding this correctly, instead of feeding in fromhost-ip I can feed in hostname and everything will work? I tried it, seems to function ok.

This is what I have now:
```
$template dbFormat,"INSERT INTO archive_bh (host, facility, priority, level, received_ts, program, msg,pid,tag) VALUES ( '%hostname%', '%syslogfacility%', '%syslogpriority%','%syslogseverity%', '%timereported:::date-mysql%', TRIM('%programname%'), TRIM('%msg%'),'%procid%', '%syslogtag%' );\n",sql
```

The downside seems to be that clicking on a hostname that hasn't been resolved to an ip address doesn't get turned into a filter. (Just an empty Host=) .. If I do manually filter for Host=hostname then it'll work. So seems like support for ingesting by hostname is almost completely there but just missing this little bit.

**Comment by proditis** [comment]
Hello @Artanicus 

Glad it worked out.

I've just pushed a fix for the empty Host. 

Feel free to try it and report back.

**Comment by Artanicus** [comment]
That fixes whitelisting, awesome!

One issue remains as far as I can see. In the logs view if I click the hostname of a hostname-only host (that's a mouthfull) the filter box only gets '=' instead of '=hostname' .. the filtering itself works, the quick population just doesn't.

**Comment by proditis** [comment]
Nice catch.

This commit should fix the filter case on syslog and archive views.

Let me know if this works for you.

**Comment by Artanicus** [comment]
Works! That's it for now what I've found to be broken, looking good.
